#! /bin/sh

make clean thwithtitle
./sqmain 1 2 SQueueLatencyRaw2 SQueueThroughputSummary
make clean th
./sqmain 1 4 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 6 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 8 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 12 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 16 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 24 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 32 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 48 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 96 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 114 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 192 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 228 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 384 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 456 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 768 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 912 SQueueLatencyRaw2 SQueueThroughputSummary
./sqmain 1 1024 SQueueLatencyRaw2 SQueueThroughputSummary

make clean thwithtitle
./sqmain 3 2 BQLatencyRaw2 BQThroughputSummary
make clean th
./sqmain 3 4,6,8,12,16 BQLatencyRaw2 BQThroughputSummary
./sqmain 3 24,32,48 BQLatencyRaw2 BQThroughputSummary
./sqmain 3 96,114,192,228,384 BQLatencyRaw2 BQThroughputSummary
./sqmain 3 456,768,912,1024 BQLatencyRaw2 BQThroughputSummary

make clean thwithtitle
./sqmain 5 2 RCULatencyRaw2 RCUThroughputSummary
make clean th
./sqmain 5 4,6,8,12,16 RCULatencyRaw2 RCUThroughputSummary
./sqmain 5 24,32,48 RCULatencyRaw2 RCUThroughputSummary
./sqmain 5 96,114,192,228,384 RCULatencyRaw2 RCUThroughputSummary
./sqmain 5 456,768,912,1024 RCULatencyRaw2 RCUThroughputSummary

make clean thwithtitle
./sqmain 4 2 MSQLatencyRaw2 MSQThroughputSummary
make clean th
./sqmain 4 4,6,8,12,16 MSQLatencyRaw2 MSQThroughputSummary
./sqmain 4 24,32,48 MSQLatencyRaw2 MSQThroughputSummary
./sqmain 4 96,114,192,228,384 MSQLatencyRaw2 MSQThroughputSummary
./sqmain 4 456,768,912,1024 MSQLatencyRaw2 MSQThroughputSummary
