mpirun -np 2 ~/mpi_queue/main
mpirun -np 4 ~/mpi_queue/main
mpirun -np 6 ~/mpi_queue/main
mpirun -np 8 ~/mpi_queue/main
mpirun -np 12 ~/mpi_queue/main
mpirun -np 16 ~/mpi_queue/main
mpirun -np 24 ~/mpi_queue/main
mpirun -np 32 ~/mpi_queue/main
mpirun -np 48 ~/mpi_queue/main
mpirun -np 57 ~/mpi_queue/main
mpirun -np 64 ~/mpi_queue/main
mpirun -np 96 ~/mpi_queue/main
mpirun -np 114 ~/mpi_queue/main
mpirun -np 192 ~/mpi_queue/main
mpirun -np 228 ~/mpi_queue/main
mpirun -np 384 ~/mpi_queue/main
mpirun -np 456 ~/mpi_queue/main
mpirun -np 512 ~/mpi_queue/main